# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c84bfc0bac7b252fa6157d9b5f655263a2b36e1a11faf166f8747ae6e2667f9a0b992ba6a76034d7d167a943b78202d17157287ea61c5108833d742cf47f3045

test:
  secret_key_base: b7e35ea1e6e47f9fcacffb3a7b4dd2bc4f4415f4e64abc3238f994941c388329c32ba329280b60f80707976b2bb5ede7751ab14fcb39c68bdadd28e96584cb8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
